1.5 Усечение
js-tasks-ru/jsbasic-20240808_azgert pull request #3
Opened 2024-08-09 12:51 UTC by iSentir

2024-08-09 13:14 UTC, jsru-1 commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2024-08-09 14:28 UTC, jsru-1 commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2024-08-12 11:37 UTC, SinimaWath requested changes

2024-08-12 11:37 UTC, SinimaWath commented on 1-module/4-task/index.js
> +  return false;
Тут надо упростить до:
`return lowerStr.includes(one.toLowerCase()) || lowerStr.includes(two.toLowerCase())`

2024-08-13 06:14 UTC, jsru-1 commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2024-08-14 12:04 UTC, SinimaWath approved these changes

2024-08-14 12:04 UTC, merged